name: PVS-Studio build analysis
on: workflow_dispatch
jobs:
  build-analyze:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install tools
        run: |
          curl -L https://cdn.pvs-studio.com/PVS-Studio_setup.exe \
          -o PVS-Studio_setup.exe
          chmod +x PVS-Studio_setup.exe
          PVS-Studio_setup.exe /verysilent /suppressmsgboxes \
          /nocloseapplications /norestart \
          /components= Core, Standalone
          PVS-Studio_Cmd.exe --userName ${{ secrets.USER_NAME }} --licenseKey ${{ secrets.LICSESE_KEY }}. 
      - name: Build
        run: |
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=On -B build .
          cmake --build build -j
      - name: Analyze
        run: |
          CompilerCommandsAnalyzer.exe analyze -f build/compile_commands.json -j
      - name: Convert report
        run: |
          PlogConverter.exe -a GA:1,2 -t Sarif -o pvs-report.sarif PVS-Studio.log
      - name: Publish report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: pvs-report.sarif
          category: PVS-Studio