name: CMake on a single platform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.13.0
        
      - name: Install Ninja
        run: choco install ninja
        
      - name: Install PVS-Studio
        run: choco install pvs-studio --package-parameters="'/standalone'"
        shell: cmd
        
      - name: PVS-Setup License
        run: |
          & "c:\Program Files (x86)\PVS-Studio\PVS-Studio_Cmd.exe" credentials --userName ${{ secrets.PVS_STUDIO_USER_NAME }} --licenseKey ${{ secrets.PVS_STUDIO_LICSESE_KEY }} &
        shell: cmd

      - name: PVS-Setup License Info
        run: |
          & "c:\Program Files (x86)\PVS-Studio\PVS-Studio_Cmd.exe" credentials --licInfo &
        shell: cmd

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/testbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DEFXC2_USE_PVS_STUDIO=ON -DEFXC2_USE_ALL_RULES=ON -G Ninja .

      - name: Build
        run: cmake --build ${{github.workspace}}/testbuild --config ${{env.BUILD_TYPE}}
 
      - name: Create compile_commands.json
        working-directory: ${{github.workspace}}/testbuild
        run: ninja -t compdb > compile_commands.json
        
      - name: Publish report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{github.workspace}}/testbuild/pvs-report.sarif
          category: PVS-Studio
